name: StygianGates
version: '${version}'
main: dev.ng5m.stygiangates.StygianGates
api-version: '1.20'
commands:
  procedure:
    description: 'the'
    permission: ng5m.sg.procedure
    usage: '/procedure <id> [args]'
  spawn:
    permission: ng5m.sg.spawn
    usage: '/spawn'
  version:
    description: 'version'
    permission: ng5m.sg.version
    usage: '/version /v'
    aliases:
      - v